blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import RecordListView, RecordDetailView, RecordCreateView, RecordUpdateView, RecordDeleteView, \
    toggle_activity

app_name = BlogConfig.name

urlpatterns = [
    path('records/', RecordListView.as_view(), name='record_list'),
    path('records/<slug:slug>/', RecordDetailView.as_view(), name='record_detail'),
    path('records_create/', RecordCreateView.as_view(), name='create_record'),
    path('records_update/<slug:slug>/', RecordUpdateView.as_view(), name='update_record'),
    path('records_delete/<slug:slug>/', RecordDeleteView.as_view(), name='delete_record'),
    path('toggle/<slug:slug>/', toggle_activity, name='toggle_activity')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing_app.urls', namespace='mailing_app')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing_app/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing_app.apps import MailingAppConfig
from mailing_app.views import MailingListView, MailingDetailView, MailingCreateView, MailingUpdateView, \
    MailingDeleteView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MessageListView, \
    MessageCreateView, MessageUpdateView, MessageDeleteView, MailingAttemptListView, set_mailing_status, HomePageView

app_name = MailingAppConfig.name

urlpatterns = [
    path('', cache_page(60)(HomePageView.as_view()), name='home'),
    path('mailing_list', MailingListView.as_view(), name='mailing_list'),
    path('mailing_detail/<int:pk>/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('client_list/', ClientListView.as_view(), name='client_list'),
    path('client_create/', ClientCreateView.as_view(), name='client_create'),
    path('client_update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client_delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_update/<int:pk>/', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>/', MessageDeleteView.as_view(), name='message_delete'),
    path('mailing_attempt_list/', MailingAttemptListView.as_view(), name='mailing_attempt_list'),
    path('set_mailing_status/<int:pk>', login_required(set_mailing_status), name='set_mailing_status')
]

mailing_app/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(max_length=50, verbose_name='контактный email', unique=True)
    full_name = models.CharField(max_length=100, verbose_name='ФИО')
    comments = models.TextField(verbose_name='комментарий', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.email} ({self.full_name})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=150, verbose_name='тема письма')
    body = models.TextField(verbose_name='тело сообщения')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.subject


class Mailing(models.Model):
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'

    FREQUENCY_CHOICES = [
        (DAILY, 'Ежедневно'),
        (WEEKLY, 'Еженедельно'),
        (MONTHLY, 'Ежемесячно')
    ]
    CREATED = 'created'
    STARTED = 'started'
    FINISHED = 'finished'
    STATUS_CHOICES = [
        (CREATED, 'Создана'),
        (STARTED, 'Запущена'),
        (FINISHED, 'Завершена')
    ]
    mailing_time = models.TimeField(verbose_name='Время рассылки')
    frequency = models.CharField(max_length=50, verbose_name='Периодичность', choices=FREQUENCY_CHOICES, default=DAILY)
    mailing_status = models.CharField(max_length=50, verbose_name='Статус рассылки', choices=STATUS_CHOICES,
                                      default=CREATED)

    clients = models.ManyToManyField(Client, verbose_name='Клиенты для рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='тема письма')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'ID: {self.id} - время рассылки: {self.mailing_time}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        permissions = [
            (
                'set_mailing_status',
                'Can set mailing status'
            ),
        ]


class MailingAttempt(models.Model):
    SENT = 'sent'
    FAILED = 'failed'
    PENDING = 'pending'

    STATUS_CHOICES = [
        (SENT, 'Отправлено'),
        (FAILED, 'Не удалось отправить'),
        (PENDING, 'В ожидании')
    ]
    time = models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')
    status = models.CharField(max_length=50, verbose_name='статус попытки', choices=STATUS_CHOICES, default=PENDING)
    server_response = models.CharField(**NULLABLE, max_length=150, verbose_name='ответ почтового сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'

mailing_app/forms.py
from django import forms
from mailing_app.models import Mailing


class StyleFormMixin:

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = '__all__'
        exclude = ('user',)

mailing_app/views.py
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, DetailView, ListView, DeleteView, TemplateView

from blog.models import Blog
from mailing_app.forms import MailingForm
from mailing_app.models import Mailing, Client, Message, MailingAttempt
from mailing_app.services import cache_message


class HomePageView(TemplateView):
    template_name = 'mailing_app/home.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['count_mailing_all'] = Mailing.objects.all().count()
        context_data['count_mailing_active'] = Mailing.objects.filter(mailing_status=Mailing.CREATED).count()
        context_data['count_unique_clients'] = Client.objects.distinct().count()
        context_data['blog'] = Blog.objects.all().order_by('?')[:3]
        return context_data


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing_app.set_mailing_status'):
            return queryset

        return queryset.filter(user=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('email', 'full_name', 'comments')
    success_url = reverse_lazy('mailing_app:client_list')

    def form_valid(self, form):
        client = form.save()
        client.user = self.request.user
        client.save()
        return super().form_valid(form)


class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    fields = ('email', 'full_name', 'comments')
    success_url = reverse_lazy('mailing_app:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing_app.change_client'))


class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing_app:client_list')

    def test_func(self):
        client = self.get_object()
        user = self.request.user
        return user.is_authenticated and (client.user == user or user.has_perm('mailing_app.delete_client'))


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.has_perm('mailing_app.view_mailing'):
            return queryset

        return queryset.filter(user=self.request.user)


class MailingDetailView(LoginRequiredMixin, DetailView):
    model = Mailing

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.request.user.has_perm('mailing_app.view_mailing') or self.request.user == self.object.user:
            return self.object
        raise HttpResponseForbidden


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing_app:mailing_list')

    def form_valid(self, form):
        if form.is_valid():
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
        return super().form_valid(form)


class MailingUpdateView(UserPassesTestMixin, UpdateView):
    model = Mailing
    fields = '__all__'
    success_url = reverse_lazy('mailing_app:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing_app.change_mailing'))


class MailingDeleteView(UserPassesTestMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing_app:mailing_list')

    def test_func(self):
        mailing = self.get_object()
        user = self.request.user
        return user.is_authenticated and (mailing.user == user or user.has_perm('mailing_app.delete_mailing'))


class MessageListView(LoginRequiredMixin, ListView):
    model = Message

    def get_queryset(self):
        queryset = cache_message(Message, 'message')
        if self.request.user.has_perm('mailing_app.set_mailing_status'):
            return queryset
        return queryset.filter(user=self.request.user)


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing_app:message_list')

    def form_valid(self, form):
        message = form.save()
        message.user = self.request.user
        message.save()
        return super().form_valid(form)


class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('mailing_app:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing_app.change_message'))


class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing_app:message_list')

    def test_func(self):
        message = self.get_object()
        user = self.request.user
        return user.is_authenticated and (message.user == user or user.has_perm('mailing_app.delete_message'))


class MailingAttemptListView(LoginRequiredMixin, ListView):
    model = MailingAttempt
    template_name = 'mailing_app/mailing_attempt_list.html'


@permission_required(perm='mailing_app.set_mailing_status')
def set_mailing_status(request, pk):
    obj = get_object_or_404(Mailing, pk=pk)
    if obj:
        obj.mailing_status = Mailing.CREATED
        obj.save()
    return redirect(request.META.get('HTTP_REFERER'))

mailing_app/templates/mailing_app/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Рассылка</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>
</head>
<body>

<header class="blog-header py-3 d-flex justify-content-center align-items-center h-100">
    <div class="container">
        <div class="row">
            {% include 'mailing_app/includes/inc_main_menu.html' %}
        </div>
    </div>
</header>
<div class="container">
    <div class="row p-5 justify-content-lg-center">
        {% block content %}
        {% endblock %}
    </div>
</div>

</body>
</html>

mailing_app/templates/mailing_app/client_confirm_delete.html
{% extends 'mailing_app/base.html' %}
{% block content %}
    <div class="container">
        <h2 class="mt-4 mb-4 text-center">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <form method="post" enctype="multipart/form-data" class="mt-3">
                            {% csrf_token %}
                            <p>
                                <strong>Вы действительно хотите удалить клиента {{ object.full_name }} ?</strong>
                            </p>
                            <div class="row justify-content-center">
                                <a href="{% url 'mailing_app:client_list' %}"
                                   class="btn btn-secondary mr-3">Отменить</a>

                                <button class="btn btn-danger" type="submit">удалить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/client_form.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Клиент</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="form-group text-center">
                                <a href="{% url 'mailing_app:client_list' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/client_list.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Клиенты</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">ФИО</th>
                    <th scope="col" style="text-align: center">Email</th>
                    <th scope="col" style="text-align: center">Комментарий</th>
                    {% if perms.mailing_app.set_mailing_status %}
                        <th scope="col" style="text-align: center">Пользователь</th>
                    {% endif %}
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.full_name }}</td>
                        <td class="text-center">{{ obj.email }}</td>
                        <td class="text-center">{{ obj.comments }}</td>
                        {% if perms.mailing_app.set_mailing_status %}
                            <td class="text-center">{{ obj.user }}</td>
                        {% endif %}

                        <td class="text-center">
                            {% if obj.user == user or user.is_superuser %}
                                <a href="{% url 'mailing_app:client_update' obj.pk %}"
                                   class="btn btn-warning">Изменить</a>
                                <a href="{% url 'mailing_app:client_delete' obj.pk %}"
                                   class="btn btn-danger">Удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing_app:client_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Добавить клиента</a>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/home.html
{% extends 'mailing_app/base.html' %}
{% load tags %}
{% block content %}
    <body>
    <div class="container-h text-center my-5 py-5">
        <div class="row">
            <div class="col-md-10 mx-auto">
                <div class="card mb-4 box-shadow">
                    <div class="card-header bg-dark text-white">
                        <h1 class="font-weight-normal">Cервис рассылок</h1>
                    </div>
                    <div class="card-body text-muted">
                        <ul class="list-unstyled mt-3 mb-4">
                            <li>Всего рассылок : {{ count_mailing_all }}</li>
                            <li>Активных рассылок всего : {{ count_mailing_active }}</li>
                            <li>Количество уникальных клиентов для рассылок : {{ count_unique_clients }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <h1>Статьи</h1>

        <div class="container">
            <div class="row">
                {% for item in blog %}
                    <div class="col-md-4 mb-4">
                        <div class="card h-100">
                            <h3 class="card-header bg-dark"><a
                                    href="{% url 'blog:record_detail' item.slug %}" style="color: white; margin: 0;">{{ item.title }}</a></h3>
                            <div class="card-body">
                                <h5 class="card-title">{{ item.body | truncatechars:100 }}</h5>
                                <img src="{% mediapath item.picture %}"
                                     class="card-img-top mx-auto d-block img-fluid" alt=""
                                     style="width: auto; height: auto;">
                                <ul>
                                    <li><a class="card-text">Просмотры: {{ item.views }}</a></li>
                                    <li><p class="card-text">Дата публикации: {{ item.created_date }}</p></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    </body>
{% endblock %}

mailing_app/templates/mailing_app/mailing_attempt_list.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Статус рассылки</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">Дата и время последней попытки</th>
                    <th scope="col" style="text-align: center">Статус попытки</th>
                    <th scope="col" style="text-align: center">Ответ почтового сервера</th>
                    <th scope="col" style="text-align: center">Рассылки</th>
                    <th scope="col" style="text-align: center">Статус рассылки</th>

                    <th scope="col" style="text-align: center">Получатели</th>
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.time }}</td>
                        <td class="text-center">{{ obj.get_status_display }}</td>
                        <td class="text-center">{{ obj.server_response }}</td>
                        <td class="text-center">{{ obj.mailing }}</td>
                        <td class="text-center">{{ obj.mailing.get_mailing_status_display }}</td>
                        <td  {% for rec in obj.mailing.clients.all %}
                            class="text-center">  {{ rec.full_name }}</td>
                        {% endfor %}

                        <td class="text-center">
                            <a href="{% url 'mailing_app:mailing_detail' obj.mailing.pk %}" class="btn btn-dark">Перейти
                                к
                                рассылке</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing_app:mailing_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Создать рассылку</a>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/mailing_confirm_delete.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <h2 class="mt-4 mb-4 text-center">Подтвердите удаление</h2>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body text-center">
                        <form method="post" enctype="multipart/form-data" class="mt-3">
                            {% csrf_token %}
                            <p>
                                <strong>Вы уверены, что хотите удалить рассылку "{{ object.message }} время
                                    рассылки {{ object.mailing_time }}"?</strong>
                            </p>
                            <div class="row justify-content-center">
                                <a href="{% url 'mailing_app:mailing_list' %}" class="btn btn-secondary mr-3">Отменить</a>

                                <button class="btn btn-danger" type="submit">удалить
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/mailing_detail.html
{% extends 'mailing_app/base.html' %}

{% block content %}

    <div class="container">
        <div class="card text-center">
            <div class="card-header">
                {{ object.message }}
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ object.mailing_time }}</h5>
                <p class="card-text">Периодичность рассылки: {{ object.get_frequency_display }}</p>
                <p class="card-text">Получатели:
                    {% for obj in object.clients.all %}
                        {{ obj.full_name }}
                    {% endfor %}

                </p>
                {% if object.user == user or user.is_superuser %}
                <a href="{% url 'mailing_app:mailing_update' object.pk %}" class="btn btn-warning">Изменить</a>
                <a href="{% url 'mailing_app:mailing_delete' object.pk %}" class="btn btn-danger">Удалить</a>
                {% endif %}
                {% if perms.mailing_app.set_mailing_status or user.is_superuser %}
                        <a class="btn btn-info" href="{% url 'mailing_app:set_mailing_status' object.pk %}">Отключить рассылку</a>
                        {% endif %}
                <br><br>
                <a href="{% url 'mailing_app:mailing_list' %}" class="btn btn-secondary">Все рассылки</a>
            </div>
            <div class="card-footer text-muted">
                Статус рассылки: {{ object.get_mailing_status_display }}

            </div>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/mailing_form.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-12">
                <div class="card shadow-sm my-4">
                    <div class="card-header text-center">
                        <h4 class="card-title">Рассылка</h4>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                {{ form.as_p }}
                            </div>
                            <div class="form-group text-center">
                                <a href="{% url 'mailing_app:mailing_list' %}"
                                   class="btn btn-secondary mt-3">Отменить</a>
                                <button class="btn btn-success mt-3" type="submit">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/mailing_list.html
{% extends 'mailing_app/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="text-center">Рассылки</h1>
        <table class="table table-striped table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col" style="text-align: center">ID</th>
                <th scope="col" style="text-align: center">Время рассылки</th>
                <th scope="col" style="text-align: center">Периодичность</th>
                <th scope="col" style="text-align: center">Статус рассылки</th>
                <th scope="col" style="text-align: center">Сообщение</th>
                <th scope="col" style="text-align: center"></th>
            </tr>
            </thead>
            <tbody class="table-group-divider table-divider-primary">

            {% for obj in object_list %}
                 {% if obj.user == user or perms.mailing_app.view_mailing %}
                <tr>
                    <th class="text-center">{{ obj.pk }}</th>
                    <td class="text-center">{{ obj.mailing_time }}</td>
                    <td class="text-center">{{ obj.get_frequency_display }}</td>
                    <td class="text-center">{{ obj.get_mailing_status_display }}</td>
                    <td class="text-center">{{ obj.message }}</td>
                    <td class="text-center"><a href="{% url 'mailing_app:mailing_detail' obj.pk %}"
                                               class="btn btn-dark">Перейти к рассылке</a>
                    </td>

                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <div class="container" style="text-align: center">

            <a href="{% url 'mailing_app:mailing_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Создать рассылку</a>
        </div>
    </div>
{% endblock %}

mailing_app/templates/mailing_app/message_list.html
{% extends 'mailing_app/base.html' %}

{% block content %}
    <div class="container">
        <h1 class="text-center">Сообщения</h1>
        <div class='table-responsive'>
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th scope="col" style="text-align: center">ID</th>
                    <th scope="col" style="text-align: center">Тема письма</th>
                    <th scope="col" style="text-align: center">Тело сообщения</th>
                    {% if perms.mailing_app.set_mailing_status %}
                        <th scope="col" style="text-align: center">Пользователь</th>
                    {% endif %}
                    <th scope="col" style="text-align: center"></th>
                </tr>
                </thead>
                <tbody>
                {% for obj in object_list %}
                    <tr>
                        <td class="text-center">{{ obj.pk }}</td>
                        <td class="text-center">{{ obj.subject }}</td>
                        <td class="text-center">{{ obj.body }}</td>
                        {% if perms.mailing_app.set_mailing_status %}
                            <td class="text-center">{{ obj.user }}</td>
                        {% endif %}

                        <td class="text-center">
                          {% if obj.user == user or user.is_superuser%}
                            <a href="{% url 'mailing_app:message_update' obj.pk %}" class="btn btn-warning">Изменить</a>
                            <a href="{% url 'mailing_app:message_delete' obj.pk %}" class="btn btn-danger">Удалить</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="container text-center">
            <a href="{% url 'mailing_app:message_create' %}" class="btn btn-outline-dark btn-lg my-3"
               style="border-radius: 25px; padding: 10px 25px; font-size: 20px; font-weight: bold;">Добавить сообщение</a>
        </div>
    </div>
{% endblock %}